language: swift
osx_image: xcode11.1
before_install:
  - export LANG=en_US.UTF-8
  - gem install cocoapods --pre --no-document --quiet
script:
  - set -o pipefail && xcodebuild -workspace Example/GooglePlacesSearchController.xcworkspace -scheme GooglePlacesSearchController-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
  - pod lib lint
